#!/usr/bin/env bash

set -o nounset # exit when reading any unset variable
set -o errexit # exit when any command returns an error

trap 'exit' INT TERM # exit when interrupted or terminated

cwd=$(pwd)

if [ ${cwd##*/} != "scalar" ]; then echo "wrong dir"; exit; fi

sbt clean

cd src/main
./scalar-on
cd $cwd
sbt package
for jar in target/*.jar; do cp $jar ${jar##*/}.on; done

cd src/main
./scalar-off
cd $cwd
sbt package
for jar in target/*.jar; do cp $jar ${jar##*/}.off; done
