#!/usr/bin/env bash

set -o nounset # exit when reading any unset variable
set -o errexit # exit when any command returns an error
#set -x # for debugging

trap 'exit' INT TERM # exit when interrupted or terminated

project=scalar

echo
ls -l ~/scalar/src/main/scala/Scalar.scala
echo

CLASSPATH=~/scalar/target/classes
CLASSPATH=$CLASSPATH:~/scalar/target/test-classes
export CLASSPATH

cwd=$(pwd)
cd ~/$project
#sbt clean
sbt compile
sbt test:compile
cd $cwd

scala $project.test.$1 "${@:2}"
